class User < ActiveRecord::Base
  # Image uploaded by user
  mount_uploader :template_picture, BookImageUploader
  # Book page generated by the user
  mount_uploader :book_page, BookPageUploader

  belongs_to :template

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end
