---
default:
    - debug: true
      open: public/Effect27.swf
      extras: -use-network=false -static-link-runtime-shared-libraries
    
library-path:
    - source/swc

source-path:
    - source/classes
    - source/libs
    
applications:
    # - class: source/classes/effects/Effect0.as
    #   output: public/Effect0.swf
    # - class: source/classes/effects/Effect1.as
    #   output: public/Effect1.swf
    # - class: source/classes/effects/Effect2.as
    #   output: public/Effect2.swf
    # - class: source/classes/effects/Effect3.as
    #   output: public/Effect3.swf
    # - class: source/classes/effects/Effect4.as
    #   output: public/Effect4.swf
    # - class: source/classes/effects/Effect5.as
    #   output: public/Effect5.swf
    # - class: source/classes/effects/Effect6.as
    #   output: public/Effect6.swf
    - class: source/classes/effects/Effect7.as
      output: public/Effect7.swf
    # - class: source/classes/effects/Effect9.as
    #   output: public/Effect9.swf
    # - class: source/classes/effects/Effect10.as
    #   output: public/Effect10.swf
    # - class: source/classes/effects/Effect11.as
    #   output: public/Effect11.swf
    # - class: source/classes/effects/Effect12.as
    #   output: public/Effect12.swf
    # - class: source/classes/effects/Effect13.as
    #   output: public/Effect13.swf
    # - class: source/classes/effects/Effect14.as
    #   output: public/Effect14.swf
    # - class: source/classes/effects/Effect15.as
    #   output: public/Effect15.swf
    # - class: source/classes/effects/Effect16.as
    #   output: public/Effect16.swf
    # - class: source/classes/effects/Effect17.as
    #   output: public/Effect17.swf
    # - class: source/classes/effects/Effect18.as
    #   output: public/Effect18.swf
    - class: source/classes/effects/Effect19.as
      output: public/Effect19.swf      
    # - class: source/classes/effects/Effect20.as
    #   output: public/Effect20.swf
    # - class: source/classes/effects/Effect21.as
    #   output: public/Effect21.swf
    # - class: source/classes/effects/Effect22.as
    #   output: public/Effect22.swf
    # - class: source/classes/effects/Effect23.as
    #   output: public/Effect23.swf
    # - class: source/classes/effects/Effect24.as
    #   output: public/Effect24.swf
    # - class: source/classes/effects/Effect25.as
    #   output: public/Effect25.swf
    # - class: source/classes/effects/Effect26.as
    #   output: public/Effect26.swf
    # - class: source/classes/effects/Effect27.as
    #   output: public/Effect27.swf
      # exclude: source/classes/Other.as

# asdoc:
#     title: "My ActionScript project"
#     footer: "My ActionScript project footer"
#     output: docs/
#     exclude-dirs: 
#       - source/classes/caurina/